<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>r9club-asio-player</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NAudio.Asio" Version="2.2.1" />
  </ItemGroup>
</Project>
